# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dns-example', ['dns', 'eslr', 'netanim', 'point-to-point', 'internet', 'network', 'applications', 'visualizer'])
    obj.source = 'dns-example.cc'

